### ISSUE TITLE
360修改绑定手机验证码无法识别

### ISSUE THREAD

**Issue by 32tian** [drakeet/SmsCodeHelper#3]
![screenshot_2015-06-19-19-31-59 1](https://cloud.githubusercontent.com/assets/7860331/8252841/2a14576a-16bc-11e5-9f92-e24efacfe57e.png)
![screenshot_2015-06-19-19-32-23 1](https://cloud.githubusercontent.com/assets/7860331/8252842/2a14bc82-16bc-11e5-8606-0a6f2863d8cb.png)

**Comment by 32tian** [comment]
QQ设备锁验证码识别是错的...
![qq 20150619230348](https://cloud.githubusercontent.com/assets/7860331/8256176/b4d0650e-16d7-11e5-9d13-8f888efba113.png)

**Comment by drakeet** [comment]
好的，感谢反馈~~
